# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - '*'

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo PR PR PR PR PR PR pipeline triggered
    echo ------------------------ test 1 1 ----------------------------------------
    echo  
    echo $(Build.Reason)
    echo Build SourceBranch - $(Build.SourceBranch)
    echo Build SourceBranchName - $(Build.SourceBranchName)
    echo ---------
    ls -la
    pwd
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
