# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - '*'

trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo PR PR PR PR PR PR pipeline triggered
    echo ------------------------ test 1 1 ----------------------------------------
    echo  
    echo $(Build.Reason)
    echo Build SourceBranch - $(Build.SourceBranch)
    echo Build SourceBranchName - $(Build.SourceBranchName)
    echo ---------
    ls -la
    pwd
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

#- name: addMessage
#  ${{ if eq(variables['Build.Reason'], 'Manual') }}:
#    value: $(Date:yyyyMMdd).$(Rev:r) Manual Build, version ${{parameters.artifactVersionOption}}_${{variables.stringBuildVersion}}
#  ${{ else }}:
#    value: ''

  #- task: SonarQubePrepare@5
  #  condition: or( and(succeeded(), eq(${{parameters.toAzureArtifacts}}, true)), and(succeeded(), eq(variables['Build.Reason'], 'PullRequest')) )
  #  displayName: 'Prepare analysis configuration'
  #  inputs:
  #    SonarQube: 'SonarQubeSC'
  #    scannerMode: 'MSBuild'
  #    ProjectKey: 'prj_key_EGYESJ'
  #    projectName: 'prjName'
  #    extraproperties: |
  #      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
  #      sonar.cs.cobertura.reportPaths=$(Agent.TempDirectory)/**/*.coverage


# restore, build, unit test, test if PR or main, publish if main, 
# DMO logic
#
#
#